/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_user_myapplication_PictureDetector */

#ifndef _Included_com_example_user_myapplication_PictureDetector
#define _Included_com_example_user_myapplication_PictureDetector
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_user_myapplication_PictureDetector_PERMISSIONS_REQUEST_CODE
#define com_example_user_myapplication_PictureDetector_PERMISSIONS_REQUEST_CODE 1000L
/*
 * Class:     com_example_user_myapplication_PictureDetector
 * Method:    Square
 * Signature: (JJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_user_myapplication_PictureDetector_Square
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_example_user_myapplication_PictureDetector
 * Method:    drawOnCamera
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_example_user_myapplication_PictureDetector_drawOnCamera
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_example_user_myapplication_PictureDetector
 * Method:    getImageFromCamera
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_example_user_myapplication_PictureDetector_getImageFromCamera
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
